/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AccessTypeRm : Indicates wether the access is via 3GPP or via non-3GPP but with the OpenAPI 'nullable: true' property.\" 



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AccessTypeRm {
}

impl AccessTypeRm {
    /// Indicates wether the access is via 3GPP or via non-3GPP but with the OpenAPI 'nullable: true' property.\" 
    pub fn new() -> AccessTypeRm {
        AccessTypeRm {
        }
    }
}


