/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AdditionalQosFlowInfo : The enumeration AdditionalQosFlowInfo provides additional QoS flow information (see clause 9.3.1.12 3GPP TS 38.413 [11]). It shall comply with the provisions defined in table 5.5.3.12-1. 



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AdditionalQosFlowInfo {
}

impl AdditionalQosFlowInfo {
    /// The enumeration AdditionalQosFlowInfo provides additional QoS flow information (see clause 9.3.1.12 3GPP TS 38.413 [11]). It shall comply with the provisions defined in table 5.5.3.12-1. 
    pub fn new() -> AdditionalQosFlowInfo {
        AdditionalQosFlowInfo {
        }
    }
}


