/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Area : Provides area information.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Area {
    #[serde(rename = "tacs", skip_serializing_if = "Option::is_none")]
    pub tacs: Option<Vec<String>>,
    /// Values are operator specific.
    #[serde(rename = "areaCode", skip_serializing_if = "Option::is_none")]
    pub area_code: Option<String>,
}

impl Area {
    /// Provides area information.
    pub fn new() -> Area {
        Area {
            tacs: None,
            area_code: None,
        }
    }
}


