/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// BackupAmfInfo : Provides details of the Backup AMF.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BackupAmfInfo {
    /// Fully Qualified Domain Name
    #[serde(rename = "backupAmf")]
    pub backup_amf: String,
    /// If present, this IE shall contain the list of GUAMI(s) (supported by the AMF) for which the backupAmf IE applies. 
    #[serde(rename = "guamiList", skip_serializing_if = "Option::is_none")]
    pub guami_list: Option<Vec<crate::models::Guami>>,
}

impl BackupAmfInfo {
    /// Provides details of the Backup AMF.
    pub fn new(backup_amf: String) -> BackupAmfInfo {
        BackupAmfInfo {
            backup_amf,
            guami_list: None,
        }
    }
}


