/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CellGlobalId : Contains a Cell Global Identification as defined in 3GPP TS 23.003, clause 4.3.1.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CellGlobalId {
    #[serde(rename = "plmnId")]
    pub plmn_id: Box<crate::models::PlmnId>,
    #[serde(rename = "lac")]
    pub lac: String,
    #[serde(rename = "cellId")]
    pub cell_id: String,
}

impl CellGlobalId {
    /// Contains a Cell Global Identification as defined in 3GPP TS 23.003, clause 4.3.1.
    pub fn new(plmn_id: crate::models::PlmnId, lac: String, cell_id: String) -> CellGlobalId {
        CellGlobalId {
            plmn_id: Box::new(plmn_id),
            lac,
            cell_id,
        }
    }
}


