/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ChangeType : Indicates the type of change to be performed.

/// Indicates the type of change to be performed.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ChangeType {
    #[serde(rename = "ADD")]
    Add,
    #[serde(rename = "MOVE")]
    Move,
    #[serde(rename = "REMOVE")]
    Remove,
    #[serde(rename = "REPLACE")]
    Replace,

}

impl ToString for ChangeType {
    fn to_string(&self) -> String {
        match self {
            Self::Add => String::from("ADD"),
            Self::Move => String::from("MOVE"),
            Self::Remove => String::from("REMOVE"),
            Self::Replace => String::from("REPLACE"),
        }
    }
}

impl Default for ChangeType {
    fn default() -> ChangeType {
        Self::Add
    }
}




