/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ChangeItem : It contains data which need to be changed.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ChangeItem {
    #[serde(rename = "op")]
    pub op: crate::models::ChangeType,
    /// contains a JSON pointer value (as defined in IETF RFC 6901) that references a target location within the resource on which the change has been applied. 
    #[serde(rename = "path")]
    pub path: String,
    /// indicates the path of the source JSON element (according to JSON Pointer syntax) being moved or copied to the location indicated by the \"path\" attribute. It shall be present if the \"op\" attribute is of value \"MOVE\". 
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<String>,
    #[serde(rename = "origValue", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub orig_value: Option<Option<serde_json::Value>>,
    #[serde(rename = "newValue", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub new_value: Option<Option<serde_json::Value>>,
}

impl ChangeItem {
    /// It contains data which need to be changed.
    pub fn new(op: crate::models::ChangeType, path: String) -> ChangeItem {
        ChangeItem {
            op,
            path,
            from: None,
            orig_value: None,
            new_value: None,
        }
    }
}


