/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Cnf : A conjunctive normal form



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Cnf {
    #[serde(rename = "cnfUnits")]
    pub cnf_units: Vec<crate::models::CnfUnit>,
}

impl Cnf {
    /// A conjunctive normal form
    pub fn new(cnf_units: Vec<crate::models::CnfUnit>) -> Cnf {
        Cnf {
            cnf_units,
        }
    }
}


