/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CnfUnit : During the processing of cnfUnits attribute, all the members in the array shall be interpreted as logically concatenated with logical \"AND\". 



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CnfUnit {
    #[serde(rename = "cnfUnit")]
    pub cnf_unit: Vec<crate::models::Atom>,
}

impl CnfUnit {
    /// During the processing of cnfUnits attribute, all the members in the array shall be interpreted as logically concatenated with logical \"AND\". 
    pub fn new(cnf_unit: Vec<crate::models::Atom>) -> CnfUnit {
        CnfUnit {
            cnf_unit,
        }
    }
}


