/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CoreNetworkType : It contains the Core Network type 5GC or EPC.

/// It contains the Core Network type 5GC or EPC.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CoreNetworkType {
    #[serde(rename = "5GC")]
    Variant5Gc,
    #[serde(rename = "EPC")]
    Epc,

}

impl ToString for CoreNetworkType {
    fn to_string(&self) -> String {
        match self {
            Self::Variant5Gc => String::from("5GC"),
            Self::Epc => String::from("EPC"),
        }
    }
}

impl Default for CoreNetworkType {
    fn default() -> CoreNetworkType {
        Self::Variant5Gc
    }
}




