/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CoreNetworkTypeRm : It contains the Core Network type 5GC or EPC but with the OpenAPI 'nullable: true' property. 



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CoreNetworkTypeRm {
}

impl CoreNetworkTypeRm {
    /// It contains the Core Network type 5GC or EPC but with the OpenAPI 'nullable: true' property. 
    pub fn new() -> CoreNetworkTypeRm {
        CoreNetworkTypeRm {
        }
    }
}


