/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// DlDataDeliveryStatus : Possible values are: - BUFFERED: The first downlink data is buffered with extended buffering matching the   source of the downlink traffic. - TRANSMITTED: The first downlink data matching the source of the downlink traffic is   transmitted after previous buffering or discarding of corresponding packet(s) because   the UE of the PDU Session becomes ACTIVE, and buffered data can be delivered to UE. - DISCARDED: The first downlink data matching the source of the downlink traffic is   discarded because the Extended Buffering time, as determined by the SMF, expires or   the amount of downlink data to be buffered is exceeded. 

/// Possible values are: - BUFFERED: The first downlink data is buffered with extended buffering matching the   source of the downlink traffic. - TRANSMITTED: The first downlink data matching the source of the downlink traffic is   transmitted after previous buffering or discarding of corresponding packet(s) because   the UE of the PDU Session becomes ACTIVE, and buffered data can be delivered to UE. - DISCARDED: The first downlink data matching the source of the downlink traffic is   discarded because the Extended Buffering time, as determined by the SMF, expires or   the amount of downlink data to be buffered is exceeded. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DlDataDeliveryStatus {
    #[serde(rename = "BUFFERED")]
    Buffered,
    #[serde(rename = "TRANSMITTED")]
    Transmitted,
    #[serde(rename = "DISCARDED")]
    Discarded,

}

impl ToString for DlDataDeliveryStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Buffered => String::from("BUFFERED"),
            Self::Transmitted => String::from("TRANSMITTED"),
            Self::Discarded => String::from("DISCARDED"),
        }
    }
}

impl Default for DlDataDeliveryStatus {
    fn default() -> DlDataDeliveryStatus {
        Self::Buffered
    }
}




