/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// DnfUnit : During the processing of dnfUnits attribute, all the members in the array shall be interpreted as logically concatenated with logical \"OR\". 



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DnfUnit {
    #[serde(rename = "dnfUnit")]
    pub dnf_unit: Vec<crate::models::Atom>,
}

impl DnfUnit {
    /// During the processing of dnfUnits attribute, all the members in the array shall be interpreted as logically concatenated with logical \"OR\". 
    pub fn new(dnf_unit: Vec<crate::models::Atom>) -> DnfUnit {
        DnfUnit {
            dnf_unit,
        }
    }
}


