/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// EasServerAddress : Represents the IP address and port of an EAS server.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EasServerAddress {
    #[serde(rename = "ip")]
    pub ip: Box<crate::models::IpAddr>,
    /// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
    #[serde(rename = "port")]
    pub port: i32,
}

impl EasServerAddress {
    /// Represents the IP address and port of an EAS server.
    pub fn new(ip: crate::models::IpAddr, port: i32) -> EasServerAddress {
        EasServerAddress {
            ip: Box::new(ip),
            port,
        }
    }
}


