/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// EasIpReplacementInfo : Contains EAS IP replacement information for a Source and a Target EAS.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EasIpReplacementInfo {
    #[serde(rename = "source")]
    pub source: Box<crate::models::EasServerAddress>,
    #[serde(rename = "target")]
    pub target: Box<crate::models::EasServerAddress>,
}

impl EasIpReplacementInfo {
    /// Contains EAS IP replacement information for a Source and a Target EAS.
    pub fn new(source: crate::models::EasServerAddress, target: crate::models::EasServerAddress) -> EasIpReplacementInfo {
        EasIpReplacementInfo {
            source: Box::new(source),
            target: Box::new(target),
        }
    }
}


