/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// EcsServerAddr : Contains the Edge Configuration Server Address Configuration Information as defined in clause 5.2.3.6.1 of 3GPP TS 23.502. 



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EcsServerAddr {
    #[serde(rename = "ecsFqdnList", skip_serializing_if = "Option::is_none")]
    pub ecs_fqdn_list: Option<Vec<String>>,
    #[serde(rename = "ecsIpAddressList", skip_serializing_if = "Option::is_none")]
    pub ecs_ip_address_list: Option<Vec<crate::models::IpAddr>>,
    #[serde(rename = "ecsUriList", skip_serializing_if = "Option::is_none")]
    pub ecs_uri_list: Option<Vec<String>>,
    #[serde(rename = "ecsProviderId", skip_serializing_if = "Option::is_none")]
    pub ecs_provider_id: Option<String>,
}

impl EcsServerAddr {
    /// Contains the Edge Configuration Server Address Configuration Information as defined in clause 5.2.3.6.1 of 3GPP TS 23.502. 
    pub fn new() -> EcsServerAddr {
        EcsServerAddr {
            ecs_fqdn_list: None,
            ecs_ip_address_list: None,
            ecs_uri_list: None,
            ecs_provider_id: None,
        }
    }
}


