/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// EventForMdt : The enumeration EventForMdt defines events triggered measurement for logged MDT in the trace. See 3GPP TS 32.422 for further description of the values. It shall comply with the provisions defined in table 5.6.3.11-1 

/// The enumeration EventForMdt defines events triggered measurement for logged MDT in the trace. See 3GPP TS 32.422 for further description of the values. It shall comply with the provisions defined in table 5.6.3.11-1 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventForMdt {
    #[serde(rename = "OUT_OF_COVERAG")]
    OutOfCoverag,
    #[serde(rename = "A2_EVENT")]
    A2Event,

}

impl ToString for EventForMdt {
    fn to_string(&self) -> String {
        match self {
            Self::OutOfCoverag => String::from("OUT_OF_COVERAG"),
            Self::A2Event => String::from("A2_EVENT"),
        }
    }
}

impl Default for EventForMdt {
    fn default() -> EventForMdt {
        Self::OutOfCoverag
    }
}




