/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// FqdnPatternMatchingRule : a matching rule for a FQDN pattern



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FqdnPatternMatchingRule {
    #[serde(rename = "regex", skip_serializing_if = "Option::is_none")]
    pub regex: Option<String>,
    #[serde(rename = "stringMatchingRule", skip_serializing_if = "Option::is_none")]
    pub string_matching_rule: Option<Box<crate::models::StringMatchingRule>>,
}

impl FqdnPatternMatchingRule {
    /// a matching rule for a FQDN pattern
    pub fn new() -> FqdnPatternMatchingRule {
        FqdnPatternMatchingRule {
            regex: None,
            string_matching_rule: None,
        }
    }
}


