/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GeoServiceArea : List of geographic area or list of civic address info



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GeoServiceArea {
    #[serde(rename = "geographicAreaList", skip_serializing_if = "Option::is_none")]
    pub geographic_area_list: Option<Vec<crate::models::GeographicArea>>,
    #[serde(rename = "civicAddressList", skip_serializing_if = "Option::is_none")]
    pub civic_address_list: Option<Vec<crate::models::CivicAddress>>,
}

impl GeoServiceArea {
    /// List of geographic area or list of civic address info
    pub fn new() -> GeoServiceArea {
        GeoServiceArea {
            geographic_area_list: None,
            civic_address_list: None,
        }
    }
}


