/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GeographicalCoordinates : Geographical coordinates.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GeographicalCoordinates {
    #[serde(rename = "lon")]
    pub lon: f64,
    #[serde(rename = "lat")]
    pub lat: f64,
}

impl GeographicalCoordinates {
    /// Geographical coordinates.
    pub fn new(lon: f64, lat: f64) -> GeographicalCoordinates {
        GeographicalCoordinates {
            lon,
            lat,
        }
    }
}


