/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// HfcNodeIdRm : This data type is defined in the same way as the 'HfcNodeId' data type, but with the OpenAPI 'nullable: true' property. 



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct HfcNodeIdRm {
    /// This IE represents the identifier of the HFC node Id as specified in CableLabs WR-TR-5WWC-ARCH. It is provisioned by the wireline operator as part of wireline operations and may contain up to six characters. 
    #[serde(rename = "hfcNId")]
    pub hfc_nid: String,
}

impl HfcNodeIdRm {
    /// This data type is defined in the same way as the 'HfcNodeId' data type, but with the OpenAPI 'nullable: true' property. 
    pub fn new(hfc_nid: String) -> HfcNodeIdRm {
        HfcNodeIdRm {
            hfc_nid,
        }
    }
}


