/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IngressTunAddrInfo : Ingress Tunnel Address Information



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IngressTunAddrInfo {
    #[serde(rename = "ingressTunAddr")]
    pub ingress_tun_addr: Vec<crate::models::TunnelAddress>,
}

impl IngressTunAddrInfo {
    /// Ingress Tunnel Address Information
    pub fn new(ingress_tun_addr: Vec<crate::models::TunnelAddress>) -> IngressTunAddrInfo {
        IngressTunAddrInfo {
            ingress_tun_addr,
        }
    }
}


