/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// InterFreqTargetInfo : Indicates the Inter Frequency Target information.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InterFreqTargetInfo {
    /// Integer value indicating the ARFCN applicable for a downlink, uplink or bi-directional (TDD) NR global frequency raster, as definition of \"ARFCN-ValueNR\" IE in clause 6.3.2 of 3GPP TS 38.331. 
    #[serde(rename = "dlCarrierFreq")]
    pub dl_carrier_freq: i32,
    /// When present, this IE shall contain a list of the physical cell identities where the UE is requested to perform measurement logging for the indicated frequency. 
    #[serde(rename = "cellIdList", skip_serializing_if = "Option::is_none")]
    pub cell_id_list: Option<Vec<i32>>,
}

impl InterFreqTargetInfo {
    /// Indicates the Inter Frequency Target information.
    pub fn new(dl_carrier_freq: i32) -> InterFreqTargetInfo {
        InterFreqTargetInfo {
            dl_carrier_freq,
            cell_id_list: None,
        }
    }
}


