/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Ipv6PrefixRm : String identifying an IPv6 address prefix formatted according to clause 4 of RFC 5952 with the OpenAPI 'nullable: true' property. IPv6Prefix data type may contain an individual /128 IPv6 address. 



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Ipv6PrefixRm {
}

impl Ipv6PrefixRm {
    /// String identifying an IPv6 address prefix formatted according to clause 4 of RFC 5952 with the OpenAPI 'nullable: true' property. IPv6Prefix data type may contain an individual /128 IPv6 address. 
    pub fn new() -> Ipv6PrefixRm {
        Ipv6PrefixRm {
        }
    }
}


