/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// JobType : The enumeration JobType defines Job Type in the trace. See 3GPP TS 32.422 for further description of the values. It shall comply with the provisions defined in table 5.6.3.3-1. 

/// The enumeration JobType defines Job Type in the trace. See 3GPP TS 32.422 for further description of the values. It shall comply with the provisions defined in table 5.6.3.3-1. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum JobType {
    #[serde(rename = "IMMEDIATE_MDT_ONLY")]
    ImmediateMdtOnly,
    #[serde(rename = "LOGGED_MDT_ONLY")]
    LoggedMdtOnly,
    #[serde(rename = "TRACE_ONLY")]
    TraceOnly,
    #[serde(rename = "IMMEDIATE_MDT_AND_TRACE")]
    ImmediateMdtAndTrace,
    #[serde(rename = "RLF_REPORTS_ONLY")]
    RlfReportsOnly,
    #[serde(rename = "RCEF_REPORTS_ONLY")]
    RcefReportsOnly,
    #[serde(rename = "LOGGED_MBSFN_MDT")]
    LoggedMbsfnMdt,

}

impl ToString for JobType {
    fn to_string(&self) -> String {
        match self {
            Self::ImmediateMdtOnly => String::from("IMMEDIATE_MDT_ONLY"),
            Self::LoggedMdtOnly => String::from("LOGGED_MDT_ONLY"),
            Self::TraceOnly => String::from("TRACE_ONLY"),
            Self::ImmediateMdtAndTrace => String::from("IMMEDIATE_MDT_AND_TRACE"),
            Self::RlfReportsOnly => String::from("RLF_REPORTS_ONLY"),
            Self::RcefReportsOnly => String::from("RCEF_REPORTS_ONLY"),
            Self::LoggedMbsfnMdt => String::from("LOGGED_MBSFN_MDT"),
        }
    }
}

impl Default for JobType {
    fn default() -> JobType {
        Self::ImmediateMdtOnly
    }
}




