/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LineType : Possible values are: - DSL: Identifies a DSL line - PON: Identifies a PON line 

/// Possible values are: - DSL: Identifies a DSL line - PON: Identifies a PON line 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LineType {
    #[serde(rename = "DSL")]
    Dsl,
    #[serde(rename = "PON")]
    Pon,

}

impl ToString for LineType {
    fn to_string(&self) -> String {
        match self {
            Self::Dsl => String::from("DSL"),
            Self::Pon => String::from("PON"),
        }
    }
}

impl Default for LineType {
    fn default() -> LineType {
        Self::Dsl
    }
}




