/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LinkRm : It contains the URI of the linked resource with the OpenAPI 'nullable: true' property. 



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LinkRm {
    /// String providing an URI formatted according to RFC 3986.
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
}

impl LinkRm {
    /// It contains the URI of the linked resource with the OpenAPI 'nullable: true' property. 
    pub fn new() -> LinkRm {
        LinkRm {
            href: None,
        }
    }
}


