/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Local3dPointUncertaintyEllipsoid : Local 3D point with uncertainty ellipsoid



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Local3dPointUncertaintyEllipsoid {
    #[serde(rename = "shape")]
    pub shape: Box<crate::models::SupportedGadShapes>,
    #[serde(rename = "localOrigin")]
    pub local_origin: Box<crate::models::LocalOrigin>,
    #[serde(rename = "point")]
    pub point: Box<crate::models::RelativeCartesianLocation>,
    #[serde(rename = "uncertaintyEllipsoid")]
    pub uncertainty_ellipsoid: Box<crate::models::UncertaintyEllipsoid>,
    /// Indicates value of confidence.
    #[serde(rename = "confidence")]
    pub confidence: i32,
}

impl Local3dPointUncertaintyEllipsoid {
    /// Local 3D point with uncertainty ellipsoid
    pub fn new(shape: crate::models::SupportedGadShapes, local_origin: crate::models::LocalOrigin, point: crate::models::RelativeCartesianLocation, uncertainty_ellipsoid: crate::models::UncertaintyEllipsoid, confidence: i32) -> Local3dPointUncertaintyEllipsoid {
        Local3dPointUncertaintyEllipsoid {
            shape: Box::new(shape),
            local_origin: Box::new(local_origin),
            point: Box::new(point),
            uncertainty_ellipsoid: Box::new(uncertainty_ellipsoid),
            confidence,
        }
    }
}


