/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Local2dPointUncertaintyEllipse : Local 2D point with uncertainty ellipse



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Local2dPointUncertaintyEllipse {
    #[serde(rename = "shape")]
    pub shape: Box<crate::models::SupportedGadShapes>,
    #[serde(rename = "localOrigin")]
    pub local_origin: Box<crate::models::LocalOrigin>,
    #[serde(rename = "point")]
    pub point: Box<crate::models::RelativeCartesianLocation>,
    #[serde(rename = "uncertaintyEllipse")]
    pub uncertainty_ellipse: Box<crate::models::UncertaintyEllipse>,
    /// Indicates value of confidence.
    #[serde(rename = "confidence")]
    pub confidence: i32,
}

impl Local2dPointUncertaintyEllipse {
    /// Local 2D point with uncertainty ellipse
    pub fn new(shape: crate::models::SupportedGadShapes, local_origin: crate::models::LocalOrigin, point: crate::models::RelativeCartesianLocation, uncertainty_ellipse: crate::models::UncertaintyEllipse, confidence: i32) -> Local2dPointUncertaintyEllipse {
        Local2dPointUncertaintyEllipse {
            shape: Box::new(shape),
            local_origin: Box::new(local_origin),
            point: Box::new(point),
            uncertainty_ellipse: Box::new(uncertainty_ellipse),
            confidence,
        }
    }
}


