/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Local2dPointUncertaintyEllipseAllOf {
    #[serde(rename = "localOrigin")]
    pub local_origin: Box<crate::models::LocalOrigin>,
    #[serde(rename = "point")]
    pub point: Box<crate::models::RelativeCartesianLocation>,
    #[serde(rename = "uncertaintyEllipse")]
    pub uncertainty_ellipse: Box<crate::models::UncertaintyEllipse>,
    /// Indicates value of confidence.
    #[serde(rename = "confidence")]
    pub confidence: i32,
}

impl Local2dPointUncertaintyEllipseAllOf {
    pub fn new(local_origin: crate::models::LocalOrigin, point: crate::models::RelativeCartesianLocation, uncertainty_ellipse: crate::models::UncertaintyEllipse, confidence: i32) -> Local2dPointUncertaintyEllipseAllOf {
        Local2dPointUncertaintyEllipseAllOf {
            local_origin: Box::new(local_origin),
            point: Box::new(point),
            uncertainty_ellipse: Box::new(uncertainty_ellipse),
            confidence,
        }
    }
}


