/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LoggingDurationNrMdt : The enumeration LoggingDurationMdt defines Logging Duration in NR for MDT in the trace. See 3GPP TS 32.422 for further description of the values. It shall comply with the provisions defined in table 5.6.3.20-1. 

/// The enumeration LoggingDurationMdt defines Logging Duration in NR for MDT in the trace. See 3GPP TS 32.422 for further description of the values. It shall comply with the provisions defined in table 5.6.3.20-1. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LoggingDurationNrMdt {
    #[serde(rename = "600")]
    Variant600,
    #[serde(rename = "1200")]
    Variant1200,
    #[serde(rename = "2400")]
    Variant2400,
    #[serde(rename = "3600")]
    Variant3600,
    #[serde(rename = "5400")]
    Variant5400,
    #[serde(rename = "7200")]
    Variant7200,

}

impl ToString for LoggingDurationNrMdt {
    fn to_string(&self) -> String {
        match self {
            Self::Variant600 => String::from("600"),
            Self::Variant1200 => String::from("1200"),
            Self::Variant2400 => String::from("2400"),
            Self::Variant3600 => String::from("3600"),
            Self::Variant5400 => String::from("5400"),
            Self::Variant7200 => String::from("7200"),
        }
    }
}

impl Default for LoggingDurationNrMdt {
    fn default() -> LoggingDurationNrMdt {
        Self::Variant600
    }
}




