/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// MbsServiceArea : MBS Service Area



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MbsServiceArea {
    /// List of NR cell Ids
    #[serde(rename = "ncgiList", skip_serializing_if = "Option::is_none")]
    pub ncgi_list: Option<Vec<crate::models::NcgiTai>>,
    /// List of tracking area Ids
    #[serde(rename = "taiList", skip_serializing_if = "Option::is_none")]
    pub tai_list: Option<Vec<crate::models::Tai>>,
}

impl MbsServiceArea {
    /// MBS Service Area
    pub fn new() -> MbsServiceArea {
        MbsServiceArea {
            ncgi_list: None,
            tai_list: None,
        }
    }
}


