/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// MbsSessionActivityStatus : Indicates the MBS session's activity status

/// Indicates the MBS session's activity status
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MbsSessionActivityStatus {
    #[serde(rename = "ACTIVE")]
    Active,
    #[serde(rename = "INACTIVE")]
    Inactive,

}

impl ToString for MbsSessionActivityStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Active => String::from("ACTIVE"),
            Self::Inactive => String::from("INACTIVE"),
        }
    }
}

impl Default for MbsSessionActivityStatus {
    fn default() -> MbsSessionActivityStatus {
        Self::Active
    }
}




