/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// MbsSessionId : MBS Session Identifier



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MbsSessionId {
    #[serde(rename = "tmgi", skip_serializing_if = "Option::is_none")]
    pub tmgi: Option<Box<crate::models::Tmgi>>,
    #[serde(rename = "ssm", skip_serializing_if = "Option::is_none")]
    pub ssm: Option<Box<crate::models::Ssm>>,
    /// This represents the Network Identifier, which together with a PLMN ID is used to identify an SNPN (see 3GPP TS 23.003 and 3GPP TS 23.501 clause 5.30.2.1). 
    #[serde(rename = "nid", skip_serializing_if = "Option::is_none")]
    pub nid: Option<String>,
}

impl MbsSessionId {
    /// MBS Session Identifier
    pub fn new() -> MbsSessionId {
        MbsSessionId {
            tmgi: None,
            ssm: None,
            nid: None,
        }
    }
}


