/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// MbsServiceType : Indicates the MBS service type of an MBS session

/// Indicates the MBS service type of an MBS session
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MbsServiceType {
    #[serde(rename = "MULTICAST")]
    Multicast,
    #[serde(rename = "BROADCAST")]
    Broadcast,

}

impl ToString for MbsServiceType {
    fn to_string(&self) -> String {
        match self {
            Self::Multicast => String::from("MULTICAST"),
            Self::Broadcast => String::from("BROADCAST"),
        }
    }
}

impl Default for MbsServiceType {
    fn default() -> MbsServiceType {
        Self::Multicast
    }
}




