/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// MbsSessionEventReportList : MBS session event report list



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MbsSessionEventReportList {
    #[serde(rename = "eventReportList")]
    pub event_report_list: Vec<crate::models::MbsSessionEventReport>,
    #[serde(rename = "notifyCorrelationId", skip_serializing_if = "Option::is_none")]
    pub notify_correlation_id: Option<String>,
}

impl MbsSessionEventReportList {
    /// MBS session event report list
    pub fn new(event_report_list: Vec<crate::models::MbsSessionEventReport>) -> MbsSessionEventReportList {
        MbsSessionEventReportList {
            event_report_list,
            notify_correlation_id: None,
        }
    }
}


