/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// MbsServiceInfo : Represent MBS Service Information.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MbsServiceInfo {
    #[serde(rename = "mbsMediaComps")]
    pub mbs_media_comps: ::std::collections::HashMap<String, crate::models::MbsMediaCompRm>,
    #[serde(rename = "mbsSdfResPrio", skip_serializing_if = "Option::is_none")]
    pub mbs_sdf_res_prio: Option<Box<crate::models::ReservPriority>>,
    /// Contains an AF application identifier.
    #[serde(rename = "afAppId", skip_serializing_if = "Option::is_none")]
    pub af_app_id: Option<String>,
    /// String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". 
    #[serde(rename = "mbsSessionAmbr", skip_serializing_if = "Option::is_none")]
    pub mbs_session_ambr: Option<String>,
}

impl MbsServiceInfo {
    /// Represent MBS Service Information.
    pub fn new(mbs_media_comps: ::std::collections::HashMap<String, crate::models::MbsMediaCompRm>) -> MbsServiceInfo {
        MbsServiceInfo {
            mbs_media_comps,
            mbs_sdf_res_prio: None,
            af_app_id: None,
            mbs_session_ambr: None,
        }
    }
}


