/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// MbsServiceAreaInfo : MBS Service Area Information for location dependent MBS session



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MbsServiceAreaInfo {
    /// Integer where the allowed values correspond to the value range of an unsigned 16-bit integer.
    #[serde(rename = "areaSessionId")]
    pub area_session_id: i32,
    #[serde(rename = "mbsServiceArea")]
    pub mbs_service_area: Box<crate::models::MbsServiceArea>,
}

impl MbsServiceAreaInfo {
    /// MBS Service Area Information for location dependent MBS session
    pub fn new(area_session_id: i32, mbs_service_area: crate::models::MbsServiceArea) -> MbsServiceAreaInfo {
        MbsServiceAreaInfo {
            area_session_id,
            mbs_service_area: Box::new(mbs_service_area),
        }
    }
}


