/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// MbsSessionEventReport : MBS session event report



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MbsSessionEventReport {
    #[serde(rename = "eventType")]
    pub event_type: crate::models::MbsSessionEventType,
    /// string with format 'date-time' as defined in OpenAPI.
    #[serde(rename = "timeStamp", skip_serializing_if = "Option::is_none")]
    pub time_stamp: Option<String>,
    #[serde(rename = "ingressTunAddrInfo", skip_serializing_if = "Option::is_none")]
    pub ingress_tun_addr_info: Option<Box<crate::models::IngressTunAddrInfo>>,
    #[serde(rename = "broadcastDelStatus", skip_serializing_if = "Option::is_none")]
    pub broadcast_del_status: Option<crate::models::BroadcastDeliveryStatus>,
}

impl MbsSessionEventReport {
    /// MBS session event report
    pub fn new(event_type: crate::models::MbsSessionEventType) -> MbsSessionEventReport {
        MbsSessionEventReport {
            event_type,
            time_stamp: None,
            ingress_tun_addr_info: None,
            broadcast_del_status: None,
        }
    }
}


