/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// MbsSessionEvent : MBS session event



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MbsSessionEvent {
    #[serde(rename = "eventType")]
    pub event_type: crate::models::MbsSessionEventType,
}

impl MbsSessionEvent {
    /// MBS session event
    pub fn new(event_type: crate::models::MbsSessionEventType) -> MbsSessionEvent {
        MbsSessionEvent {
            event_type,
        }
    }
}


