/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// MbsfnArea : Contains an MBSFN area information.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MbsfnArea {
    /// This IE shall contain the MBSFN Area ID.
    #[serde(rename = "mbsfnAreaId", skip_serializing_if = "Option::is_none")]
    pub mbsfn_area_id: Option<i32>,
    /// When present, this IE shall contain the Carrier Frequency (EARFCN).
    #[serde(rename = "carrierFrequency", skip_serializing_if = "Option::is_none")]
    pub carrier_frequency: Option<i32>,
}

impl MbsfnArea {
    /// Contains an MBSFN area information.
    pub fn new() -> MbsfnArea {
        MbsfnArea {
            mbsfn_area_id: None,
            carrier_frequency: None,
        }
    }
}


