/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// MeasurementLteForMdt : The enumeration MeasurementLteForMdt defines Measurements used for MDT in LTE in the trace. See 3GPP TS 32.422 for further description of the values. It shall comply with the provisions defined in table 5.6.3.5-1. 

/// The enumeration MeasurementLteForMdt defines Measurements used for MDT in LTE in the trace. See 3GPP TS 32.422 for further description of the values. It shall comply with the provisions defined in table 5.6.3.5-1. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MeasurementLteForMdt {
    #[serde(rename = "M1")]
    M1,
    #[serde(rename = "M2")]
    M2,
    #[serde(rename = "M3")]
    M3,
    #[serde(rename = "M4_DL")]
    M4Dl,
    #[serde(rename = "M4_UL")]
    M4Ul,
    #[serde(rename = "M5_DL")]
    M5Dl,
    #[serde(rename = "M5_UL")]
    M5Ul,
    #[serde(rename = "M6_DL")]
    M6Dl,
    #[serde(rename = "M6_UL")]
    M6Ul,
    #[serde(rename = "M7_DL")]
    M7Dl,
    #[serde(rename = "M7_UL")]
    M7Ul,
    #[serde(rename = "M8")]
    M8,
    #[serde(rename = "M9")]
    M9,

}

impl ToString for MeasurementLteForMdt {
    fn to_string(&self) -> String {
        match self {
            Self::M1 => String::from("M1"),
            Self::M2 => String::from("M2"),
            Self::M3 => String::from("M3"),
            Self::M4Dl => String::from("M4_DL"),
            Self::M4Ul => String::from("M4_UL"),
            Self::M5Dl => String::from("M5_DL"),
            Self::M5Ul => String::from("M5_UL"),
            Self::M6Dl => String::from("M6_DL"),
            Self::M6Ul => String::from("M6_UL"),
            Self::M7Dl => String::from("M7_DL"),
            Self::M7Ul => String::from("M7_UL"),
            Self::M8 => String::from("M8"),
            Self::M9 => String::from("M9"),
        }
    }
}

impl Default for MeasurementLteForMdt {
    fn default() -> MeasurementLteForMdt {
        Self::M1
    }
}




