/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// MeasurementPeriodLteMdt : The enumeration MeasurementPeriodLteMdt defines Measurement period LTE for MDT in the trace. See 3GPP TS 32.422 for further description of the values. It shall comply with the provisions defined in table 5.6.3.16-1. 

/// The enumeration MeasurementPeriodLteMdt defines Measurement period LTE for MDT in the trace. See 3GPP TS 32.422 for further description of the values. It shall comply with the provisions defined in table 5.6.3.16-1. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MeasurementPeriodLteMdt {
    #[serde(rename = "1024")]
    Variant1024,
    #[serde(rename = "1280")]
    Variant1280,
    #[serde(rename = "2048")]
    Variant2048,
    #[serde(rename = "2560")]
    Variant2560,
    #[serde(rename = "5120")]
    Variant5120,
    #[serde(rename = "10240")]
    Variant10240,
    #[serde(rename = "60000")]
    Variant60000,

}

impl ToString for MeasurementPeriodLteMdt {
    fn to_string(&self) -> String {
        match self {
            Self::Variant1024 => String::from("1024"),
            Self::Variant1280 => String::from("1280"),
            Self::Variant2048 => String::from("2048"),
            Self::Variant2560 => String::from("2560"),
            Self::Variant5120 => String::from("5120"),
            Self::Variant10240 => String::from("10240"),
            Self::Variant60000 => String::from("60000"),
        }
    }
}

impl Default for MeasurementPeriodLteMdt {
    fn default() -> MeasurementPeriodLteMdt {
        Self::Variant1024
    }
}




