/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// NgApCause : Represents the NGAP cause.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NgApCause {
    /// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
    #[serde(rename = "group")]
    pub group: i32,
    /// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
    #[serde(rename = "value")]
    pub value: i32,
}

impl NgApCause {
    /// Represents the NGAP cause.
    pub fn new(group: i32, value: i32) -> NgApCause {
        NgApCause {
            group,
            value,
        }
    }
}


