/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// NonDynamic5Qi : It indicates the QoS Characteristics for a standardized or pre-configured 5QI for downlink and uplink. 



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NonDynamic5Qi {
    /// Unsigned integer indicating the 5QI Priority Level (see clauses 5.7.3.3 and 5.7.4 of 3GPP TS 23.501, within the range 1 to 127.Values are ordered in decreasing order of priority, i.e. with 1 as the highest priority and 127 as the lowest priority. 
    #[serde(rename = "priorityLevel", skip_serializing_if = "Option::is_none")]
    pub priority_level: Option<i32>,
    /// Unsigned integer indicating Averaging Window (see clause 5.7.3.6 and 5.7.4 of 3GPP TS 23.501), expressed in milliseconds.
    #[serde(rename = "averWindow", skip_serializing_if = "Option::is_none")]
    pub aver_window: Option<i32>,
    /// Unsigned integer indicating Maximum Data Burst Volume (see clauses 5.7.3.7 and 5.7.4 of 3GPP TS 23.501), expressed in Bytes. 
    #[serde(rename = "maxDataBurstVol", skip_serializing_if = "Option::is_none")]
    pub max_data_burst_vol: Option<i32>,
    /// Unsigned integer indicating Maximum Data Burst Volume (see clauses 5.7.3.7 and 5.7.4 of 3GPP TS 23.501), expressed in Bytes. 
    #[serde(rename = "extMaxDataBurstVol", skip_serializing_if = "Option::is_none")]
    pub ext_max_data_burst_vol: Option<i32>,
    /// Unsigned integer indicating Packet Delay Budget (see clauses 5.7.3.4 and 5.7.4 of 3GPP TS 23.501 [8])), expressed in 0.01 milliseconds. 
    #[serde(rename = "cnPacketDelayBudgetDl", skip_serializing_if = "Option::is_none")]
    pub cn_packet_delay_budget_dl: Option<i32>,
    /// Unsigned integer indicating Packet Delay Budget (see clauses 5.7.3.4 and 5.7.4 of 3GPP TS 23.501 [8])), expressed in 0.01 milliseconds. 
    #[serde(rename = "cnPacketDelayBudgetUl", skip_serializing_if = "Option::is_none")]
    pub cn_packet_delay_budget_ul: Option<i32>,
}

impl NonDynamic5Qi {
    /// It indicates the QoS Characteristics for a standardized or pre-configured 5QI for downlink and uplink. 
    pub fn new() -> NonDynamic5Qi {
        NonDynamic5Qi {
            priority_level: None,
            aver_window: None,
            max_data_burst_vol: None,
            ext_max_data_burst_vol: None,
            cn_packet_delay_budget_dl: None,
            cn_packet_delay_budget_ul: None,
        }
    }
}


