/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NotificationControlAnyOf {
    #[serde(rename = "REQUESTED")]
    Requested,
    #[serde(rename = "NOT_REQUESTED")]
    NotRequested,

}

impl ToString for NotificationControlAnyOf {
    fn to_string(&self) -> String {
        match self {
            Self::Requested => String::from("REQUESTED"),
            Self::NotRequested => String::from("NOT_REQUESTED"),
        }
    }
}

impl Default for NotificationControlAnyOf {
    fn default() -> NotificationControlAnyOf {
        Self::Requested
    }
}




