/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// NotifyItem : Indicates changes on a resource.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NotifyItem {
    /// String providing an URI formatted according to RFC 3986.
    #[serde(rename = "resourceId")]
    pub resource_id: String,
    #[serde(rename = "changes")]
    pub changes: Vec<crate::models::ChangeItem>,
}

impl NotifyItem {
    /// Indicates changes on a resource.
    pub fn new(resource_id: String, changes: Vec<crate::models::ChangeItem>) -> NotifyItem {
        NotifyItem {
            resource_id,
            changes,
        }
    }
}


