/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// NssaaStatusRm : This data type is defined in the same way as the 'NssaaStatus' data type, but with the OpenAPI 'nullable: true' property. 



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NssaaStatusRm {
    #[serde(rename = "snssai")]
    pub snssai: Box<crate::models::Snssai>,
    #[serde(rename = "status")]
    pub status: crate::models::AuthStatus,
}

impl NssaaStatusRm {
    /// This data type is defined in the same way as the 'NssaaStatus' data type, but with the OpenAPI 'nullable: true' property. 
    pub fn new(snssai: crate::models::Snssai, status: crate::models::AuthStatus) -> NssaaStatusRm {
        NssaaStatusRm {
            snssai: Box::new(snssai),
            status,
        }
    }
}


