/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// NssaaStatus : contains the Subscribed S-NSSAI subject to NSSAA procedure and the status.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NssaaStatus {
    #[serde(rename = "snssai")]
    pub snssai: Box<crate::models::Snssai>,
    #[serde(rename = "status")]
    pub status: crate::models::AuthStatus,
}

impl NssaaStatus {
    /// contains the Subscribed S-NSSAI subject to NSSAA procedure and the status.
    pub fn new(snssai: crate::models::Snssai, status: crate::models::AuthStatus) -> NssaaStatus {
        NssaaStatus {
            snssai: Box::new(snssai),
            status,
        }
    }
}


