/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// NullValue : JSON's null value.

/// JSON's null value.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NullValue {
    #[serde(rename = "null")]
    Null,

}

impl ToString for NullValue {
    fn to_string(&self) -> String {
        match self {
            Self::Null => String::from("null"),
        }
    }
}

impl Default for NullValue {
    fn default() -> NullValue {
        Self::Null
    }
}




