/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// OdbData : Contains information regarding operater  determined  barring.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OdbData {
    #[serde(rename = "roamingOdb", skip_serializing_if = "Option::is_none")]
    pub roaming_odb: Option<Box<crate::models::RoamingOdb>>,
}

impl OdbData {
    /// Contains information regarding operater  determined  barring.
    pub fn new() -> OdbData {
        OdbData {
            roaming_odb: None,
        }
    }
}


