/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PatchOperation : Operations as defined in IETF RFC 6902.

/// Operations as defined in IETF RFC 6902.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PatchOperation {
    #[serde(rename = "add")]
    Add,
    #[serde(rename = "copy")]
    Copy,
    #[serde(rename = "move")]
    Move,
    #[serde(rename = "remove")]
    Remove,
    #[serde(rename = "replace")]
    Replace,
    #[serde(rename = "test")]
    Test,

}

impl ToString for PatchOperation {
    fn to_string(&self) -> String {
        match self {
            Self::Add => String::from("add"),
            Self::Copy => String::from("copy"),
            Self::Move => String::from("move"),
            Self::Remove => String::from("remove"),
            Self::Replace => String::from("replace"),
            Self::Test => String::from("test"),
        }
    }
}

impl Default for PatchOperation {
    fn default() -> PatchOperation {
        Self::Add
    }
}




