/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Pc5QoSPara : Contains policy data on the PC5 QoS parameters.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Pc5QoSPara {
    #[serde(rename = "pc5QosFlowList")]
    pub pc5_qos_flow_list: Vec<crate::models::Pc5QosFlowItem>,
    /// String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". 
    #[serde(rename = "pc5LinkAmbr", skip_serializing_if = "Option::is_none")]
    pub pc5_link_ambr: Option<String>,
}

impl Pc5QoSPara {
    /// Contains policy data on the PC5 QoS parameters.
    pub fn new(pc5_qos_flow_list: Vec<crate::models::Pc5QosFlowItem>) -> Pc5QoSPara {
        Pc5QoSPara {
            pc5_qos_flow_list,
            pc5_link_ambr: None,
        }
    }
}


