/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Pc5FlowBitRates : it shall represent the PC5 Flow Bit Rates



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Pc5FlowBitRates {
    /// String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". 
    #[serde(rename = "guaFbr", skip_serializing_if = "Option::is_none")]
    pub gua_fbr: Option<String>,
    /// String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". 
    #[serde(rename = "maxFbr", skip_serializing_if = "Option::is_none")]
    pub max_fbr: Option<String>,
}

impl Pc5FlowBitRates {
    /// it shall represent the PC5 Flow Bit Rates
    pub fn new() -> Pc5FlowBitRates {
        Pc5FlowBitRates {
            gua_fbr: None,
            max_fbr: None,
        }
    }
}


