/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Pc5QosFlowItem : Contains a PC5 QOS flow.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Pc5QosFlowItem {
    /// Unsigned integer representing a 5G QoS Identifier (see clause 5.7.2.1 of 3GPP TS 23.501, within the range 0 to 255. 
    #[serde(rename = "pqi")]
    pub pqi: i32,
    #[serde(rename = "pc5FlowBitRates", skip_serializing_if = "Option::is_none")]
    pub pc5_flow_bit_rates: Option<Box<crate::models::Pc5FlowBitRates>>,
    /// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
    #[serde(rename = "range", skip_serializing_if = "Option::is_none")]
    pub range: Option<i32>,
}

impl Pc5QosFlowItem {
    /// Contains a PC5 QOS flow.
    pub fn new(pqi: i32) -> Pc5QosFlowItem {
        Pc5QosFlowItem {
            pqi,
            pc5_flow_bit_rates: None,
            range: None,
        }
    }
}


