/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PcfUeCallbackInfo : Contains the PCF for the UE information necessary for the PCF for the PDU session to send SM Policy Association Establishment and Termination events. 



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PcfUeCallbackInfo {
    /// String providing an URI formatted according to RFC 3986.
    #[serde(rename = "callbackUri")]
    pub callback_uri: String,
    #[serde(rename = "bindingInfo", skip_serializing_if = "Option::is_none")]
    pub binding_info: Option<String>,
}

impl PcfUeCallbackInfo {
    /// Contains the PCF for the UE information necessary for the PCF for the PDU session to send SM Policy Association Establishment and Termination events. 
    pub fn new(callback_uri: String) -> PcfUeCallbackInfo {
        PcfUeCallbackInfo {
            callback_uri,
            binding_info: None,
        }
    }
}


