/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PduSessionInfo : indicates the DNN and S-NSSAI combination of a PDU session.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PduSessionInfo {
    #[serde(rename = "snssai")]
    pub snssai: Box<crate::models::Snssai>,
    /// String representing a Data Network as defined in clause 9A of 3GPP TS 23.003; it shall contain either a DNN Network Identifier, or a full DNN with both the Network Identifier and Operator Identifier, as specified in 3GPP TS 23.003 clause 9.1.1 and 9.1.2. It shall be coded as string in which the labels are separated by dots (e.g. \"Label1.Label2.Label3\"). 
    #[serde(rename = "dnn")]
    pub dnn: String,
}

impl PduSessionInfo {
    /// indicates the DNN and S-NSSAI combination of a PDU session.
    pub fn new(snssai: crate::models::Snssai, dnn: String) -> PduSessionInfo {
        PduSessionInfo {
            snssai: Box::new(snssai),
            dnn,
        }
    }
}


