/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PlmnIdRm : This data type is defined in the same way as the 'PlmnId' data type, but with the OpenAPI 'nullable: true' property. 



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PlmnIdRm {
    /// Mobile Country Code part of the PLMN, comprising 3 digits, as defined in clause 9.3.3.5 of 3GPP TS 38.413. 
    #[serde(rename = "mcc")]
    pub mcc: String,
    /// Mobile Network Code part of the PLMN, comprising 2 or 3 digits, as defined in clause 9.3.3.5 of 3GPP TS 38.413.
    #[serde(rename = "mnc")]
    pub mnc: String,
}

impl PlmnIdRm {
    /// This data type is defined in the same way as the 'PlmnId' data type, but with the OpenAPI 'nullable: true' property. 
    pub fn new(mcc: String, mnc: String) -> PlmnIdRm {
        PlmnIdRm {
            mcc,
            mnc,
        }
    }
}


