/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PointAltitudeAllOf {
    #[serde(rename = "point")]
    pub point: Box<crate::models::GeographicalCoordinates>,
    /// Indicates value of altitude.
    #[serde(rename = "altitude")]
    pub altitude: f64,
}

impl PointAltitudeAllOf {
    pub fn new(point: crate::models::GeographicalCoordinates, altitude: f64) -> PointAltitudeAllOf {
        PointAltitudeAllOf {
            point: Box::new(point),
            altitude,
        }
    }
}


