/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PointUncertaintyCircleAllOf {
    #[serde(rename = "point")]
    pub point: Box<crate::models::GeographicalCoordinates>,
    /// Indicates value of uncertainty.
    #[serde(rename = "uncertainty")]
    pub uncertainty: f32,
}

impl PointUncertaintyCircleAllOf {
    pub fn new(point: crate::models::GeographicalCoordinates, uncertainty: f32) -> PointUncertaintyCircleAllOf {
        PointUncertaintyCircleAllOf {
            point: Box::new(point),
            uncertainty,
        }
    }
}


