/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PointUncertaintyEllipse : Ellipsoid point with uncertainty ellipse.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PointUncertaintyEllipse {
    #[serde(rename = "shape")]
    pub shape: Box<crate::models::SupportedGadShapes>,
    #[serde(rename = "point")]
    pub point: Box<crate::models::GeographicalCoordinates>,
    #[serde(rename = "uncertaintyEllipse")]
    pub uncertainty_ellipse: Box<crate::models::UncertaintyEllipse>,
    /// Indicates value of confidence.
    #[serde(rename = "confidence")]
    pub confidence: i32,
}

impl PointUncertaintyEllipse {
    /// Ellipsoid point with uncertainty ellipse.
    pub fn new(shape: crate::models::SupportedGadShapes, point: crate::models::GeographicalCoordinates, uncertainty_ellipse: crate::models::UncertaintyEllipse, confidence: i32) -> PointUncertaintyEllipse {
        PointUncertaintyEllipse {
            shape: Box::new(shape),
            point: Box::new(point),
            uncertainty_ellipse: Box::new(uncertainty_ellipse),
            confidence,
        }
    }
}


