/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PointAllOf {
    #[serde(rename = "point")]
    pub point: Box<crate::models::GeographicalCoordinates>,
}

impl PointAllOf {
    pub fn new(point: crate::models::GeographicalCoordinates) -> PointAllOf {
        PointAllOf {
            point: Box::new(point),
        }
    }
}


