/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PointAltitude : Ellipsoid point with altitude.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PointAltitude {
    #[serde(rename = "shape")]
    pub shape: Box<crate::models::SupportedGadShapes>,
    #[serde(rename = "point")]
    pub point: Box<crate::models::GeographicalCoordinates>,
    /// Indicates value of altitude.
    #[serde(rename = "altitude")]
    pub altitude: f64,
}

impl PointAltitude {
    /// Ellipsoid point with altitude.
    pub fn new(shape: crate::models::SupportedGadShapes, point: crate::models::GeographicalCoordinates, altitude: f64) -> PointAltitude {
        PointAltitude {
            shape: Box::new(shape),
            point: Box::new(point),
            altitude,
        }
    }
}


