/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Polygon : Polygon.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Polygon {
    #[serde(rename = "shape")]
    pub shape: Box<crate::models::SupportedGadShapes>,
    /// List of points.
    #[serde(rename = "pointList")]
    pub point_list: Vec<crate::models::GeographicalCoordinates>,
}

impl Polygon {
    /// Polygon.
    pub fn new(shape: crate::models::SupportedGadShapes, point_list: Vec<crate::models::GeographicalCoordinates>) -> Polygon {
        Polygon {
            shape: Box::new(shape),
            point_list,
        }
    }
}


