/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PolygonAllOf {
    /// List of points.
    #[serde(rename = "pointList")]
    pub point_list: Vec<crate::models::GeographicalCoordinates>,
}

impl PolygonAllOf {
    pub fn new(point_list: Vec<crate::models::GeographicalCoordinates>) -> PolygonAllOf {
        PolygonAllOf {
            point_list,
        }
    }
}


