/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PositioningMethodMdt : The enumeration LoggingDurationMdt defines Logging Duration for MDT in the trace. See 3GPP TS 32.422 for further description of the values. It shall comply with the provisions defined in table 5.6.3.13-1. 

/// The enumeration LoggingDurationMdt defines Logging Duration for MDT in the trace. See 3GPP TS 32.422 for further description of the values. It shall comply with the provisions defined in table 5.6.3.13-1. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PositioningMethodMdt {
    #[serde(rename = "GNSS")]
    Gnss,
    #[serde(rename = "E_CELL_ID")]
    ECellId,

}

impl ToString for PositioningMethodMdt {
    fn to_string(&self) -> String {
        match self {
            Self::Gnss => String::from("GNSS"),
            Self::ECellId => String::from("E_CELL_ID"),
        }
    }
}

impl Default for PositioningMethodMdt {
    fn default() -> PositioningMethodMdt {
        Self::Gnss
    }
}




