/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PreemptionCapabilityAnyOf {
    #[serde(rename = "NOT_PREEMPT")]
    NotPreempt,
    #[serde(rename = "MAY_PREEMPT")]
    MayPreempt,

}

impl ToString for PreemptionCapabilityAnyOf {
    fn to_string(&self) -> String {
        match self {
            Self::NotPreempt => String::from("NOT_PREEMPT"),
            Self::MayPreempt => String::from("MAY_PREEMPT"),
        }
    }
}

impl Default for PreemptionCapabilityAnyOf {
    fn default() -> PreemptionCapabilityAnyOf {
        Self::NotPreempt
    }
}




