/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ProseServiceAuth : Indicates whether the UE is authorized to use ProSe Direct Discovery, ProSe Direct Communication, or both. 



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProseServiceAuth {
    #[serde(rename = "proseDirectDiscoveryAuth", skip_serializing_if = "Option::is_none")]
    pub prose_direct_discovery_auth: Option<crate::models::UeAuth>,
    #[serde(rename = "proseDirectCommunicationAuth", skip_serializing_if = "Option::is_none")]
    pub prose_direct_communication_auth: Option<crate::models::UeAuth>,
}

impl ProseServiceAuth {
    /// Indicates whether the UE is authorized to use ProSe Direct Discovery, ProSe Direct Communication, or both. 
    pub fn new() -> ProseServiceAuth {
        ProseServiceAuth {
            prose_direct_discovery_auth: None,
            prose_direct_communication_auth: None,
        }
    }
}


