/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum QosResourceTypeAnyOf {
    #[serde(rename = "NON_GBR")]
    NonGbr,
    #[serde(rename = "NON_CRITICAL_GBR")]
    NonCriticalGbr,
    #[serde(rename = "CRITICAL_GBR")]
    CriticalGbr,

}

impl ToString for QosResourceTypeAnyOf {
    fn to_string(&self) -> String {
        match self {
            Self::NonGbr => String::from("NON_GBR"),
            Self::NonCriticalGbr => String::from("NON_CRITICAL_GBR"),
            Self::CriticalGbr => String::from("CRITICAL_GBR"),
        }
    }
}

impl Default for QosResourceTypeAnyOf {
    fn default() -> QosResourceTypeAnyOf {
        Self::NonGbr
    }
}




