/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// QosResourceTypeRm : This enumeration is defined in the same way as the 'QosResourceType' enumeration, but with the OpenAPI 'nullable: true' property. \" 



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct QosResourceTypeRm {
}

impl QosResourceTypeRm {
    /// This enumeration is defined in the same way as the 'QosResourceType' enumeration, but with the OpenAPI 'nullable: true' property. \" 
    pub fn new() -> QosResourceTypeRm {
        QosResourceTypeRm {
        }
    }
}


