/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RefToBinaryData : This parameter provides information about the referenced binary body data.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RefToBinaryData {
    /// This IE shall contain the value of the Content-ID header of the referenced binary body part. 
    #[serde(rename = "contentId")]
    pub content_id: String,
}

impl RefToBinaryData {
    /// This parameter provides information about the referenced binary body data.
    pub fn new(content_id: String) -> RefToBinaryData {
        RefToBinaryData {
            content_id,
        }
    }
}


