/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ReflectiveQoSAttribute : The enumeration ReflectiveQosAttribute indicates whether certain traffic of the QoS flow may be subject to Reflective QoS (see clause 5.7.2.3 of 3GPP TS 23.501). It shall comply with the provisions defined in table 5.5.3.3-1. 

/// The enumeration ReflectiveQosAttribute indicates whether certain traffic of the QoS flow may be subject to Reflective QoS (see clause 5.7.2.3 of 3GPP TS 23.501). It shall comply with the provisions defined in table 5.5.3.3-1. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReflectiveQoSAttribute {
    #[serde(rename = "RQOS")]
    Rqos,
    #[serde(rename = "NO_RQOS")]
    NoRqos,

}

impl ToString for ReflectiveQoSAttribute {
    fn to_string(&self) -> String {
        match self {
            Self::Rqos => String::from("RQOS"),
            Self::NoRqos => String::from("NO_RQOS"),
        }
    }
}

impl Default for ReflectiveQoSAttribute {
    fn default() -> ReflectiveQoSAttribute {
        Self::Rqos
    }
}




