/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RelativeCartesianLocation : Relative Cartesian Location



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RelativeCartesianLocation {
    /// string with format 'float' as defined in OpenAPI.
    #[serde(rename = "x")]
    pub x: f32,
    /// string with format 'float' as defined in OpenAPI.
    #[serde(rename = "y")]
    pub y: f32,
    /// string with format 'float' as defined in OpenAPI.
    #[serde(rename = "z", skip_serializing_if = "Option::is_none")]
    pub z: Option<f32>,
}

impl RelativeCartesianLocation {
    /// Relative Cartesian Location
    pub fn new(x: f32, y: f32) -> RelativeCartesianLocation {
        RelativeCartesianLocation {
            x,
            y,
            z: None,
        }
    }
}


