/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ReportAmountMdt : The enumeration ReportAmountMdt defines Report Amount for MDT in the trace. See 3GPP TS 32.422 for further description of the values. It shall comply with the provisions defined in table 5.6.3.10-1. 

/// The enumeration ReportAmountMdt defines Report Amount for MDT in the trace. See 3GPP TS 32.422 for further description of the values. It shall comply with the provisions defined in table 5.6.3.10-1. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReportAmountMdt {
    #[serde(rename = "1")]
    Variant1,
    #[serde(rename = "2")]
    Variant2,
    #[serde(rename = "4")]
    Variant4,
    #[serde(rename = "8")]
    Variant8,
    #[serde(rename = "16")]
    Variant16,
    #[serde(rename = "32")]
    Variant32,
    #[serde(rename = "64")]
    Variant64,
    #[serde(rename = "infinity")]
    Infinity,

}

impl ToString for ReportAmountMdt {
    fn to_string(&self) -> String {
        match self {
            Self::Variant1 => String::from("1"),
            Self::Variant2 => String::from("2"),
            Self::Variant4 => String::from("4"),
            Self::Variant8 => String::from("8"),
            Self::Variant16 => String::from("16"),
            Self::Variant32 => String::from("32"),
            Self::Variant64 => String::from("64"),
            Self::Infinity => String::from("infinity"),
        }
    }
}

impl Default for ReportAmountMdt {
    fn default() -> ReportAmountMdt {
        Self::Variant1
    }
}




