/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ReportIntervalNrMdt : The enumeration ReportIntervalNrMdt defines Report Interval in NR for MDT in the trace. See 3GPP TS 32.422 for further description of the values. It shall comply with the provisions defined in table 5.6.3.17-1. 

/// The enumeration ReportIntervalNrMdt defines Report Interval in NR for MDT in the trace. See 3GPP TS 32.422 for further description of the values. It shall comply with the provisions defined in table 5.6.3.17-1. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReportIntervalNrMdt {
    #[serde(rename = "120")]
    Variant120,
    #[serde(rename = "240")]
    Variant240,
    #[serde(rename = "480")]
    Variant480,
    #[serde(rename = "640")]
    Variant640,
    #[serde(rename = "1024")]
    Variant1024,
    #[serde(rename = "2048")]
    Variant2048,
    #[serde(rename = "5120")]
    Variant5120,
    #[serde(rename = "10240")]
    Variant10240,
    #[serde(rename = "20480")]
    Variant20480,
    #[serde(rename = "40960")]
    Variant40960,
    #[serde(rename = "60000")]
    Variant60000,
    #[serde(rename = "360000")]
    Variant360000,
    #[serde(rename = "720000")]
    Variant720000,
    #[serde(rename = "1800000")]
    Variant1800000,
    #[serde(rename = "3600000")]
    Variant3600000,

}

impl ToString for ReportIntervalNrMdt {
    fn to_string(&self) -> String {
        match self {
            Self::Variant120 => String::from("120"),
            Self::Variant240 => String::from("240"),
            Self::Variant480 => String::from("480"),
            Self::Variant640 => String::from("640"),
            Self::Variant1024 => String::from("1024"),
            Self::Variant2048 => String::from("2048"),
            Self::Variant5120 => String::from("5120"),
            Self::Variant10240 => String::from("10240"),
            Self::Variant20480 => String::from("20480"),
            Self::Variant40960 => String::from("40960"),
            Self::Variant60000 => String::from("60000"),
            Self::Variant360000 => String::from("360000"),
            Self::Variant720000 => String::from("720000"),
            Self::Variant1800000 => String::from("1800000"),
            Self::Variant3600000 => String::from("3600000"),
        }
    }
}

impl Default for ReportIntervalNrMdt {
    fn default() -> ReportIntervalNrMdt {
        Self::Variant120
    }
}




