/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ReportTypeMdt : The enumeration ReportTypeMdt defines Report Type for logged MDT in the trace. See 3GPP TS 32.422 for further description of the values. It shall comply with the provisions defined in table 5.6.3.4-1. 

/// The enumeration ReportTypeMdt defines Report Type for logged MDT in the trace. See 3GPP TS 32.422 for further description of the values. It shall comply with the provisions defined in table 5.6.3.4-1. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReportTypeMdt {
    #[serde(rename = "PERIODICAL")]
    Periodical,
    #[serde(rename = "EVENT_TRIGGED")]
    EventTrigged,

}

impl ToString for ReportTypeMdt {
    fn to_string(&self) -> String {
        match self {
            Self::Periodical => String::from("PERIODICAL"),
            Self::EventTrigged => String::from("EVENT_TRIGGED"),
        }
    }
}

impl Default for ReportTypeMdt {
    fn default() -> ReportTypeMdt {
        Self::Periodical
    }
}




