/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReservPriorityAnyOf {
    #[serde(rename = "PRIO_1")]
    Variant1,
    #[serde(rename = "PRIO_2")]
    Variant2,
    #[serde(rename = "PRIO_3")]
    Variant3,
    #[serde(rename = "PRIO_4")]
    Variant4,
    #[serde(rename = "PRIO_5")]
    Variant5,
    #[serde(rename = "PRIO_6")]
    Variant6,
    #[serde(rename = "PRIO_7")]
    Variant7,
    #[serde(rename = "PRIO_8")]
    Variant8,
    #[serde(rename = "PRIO_9")]
    Variant9,
    #[serde(rename = "PRIO_10")]
    Variant10,
    #[serde(rename = "PRIO_11")]
    Variant11,
    #[serde(rename = "PRIO_12")]
    Variant12,
    #[serde(rename = "PRIO_13")]
    Variant13,
    #[serde(rename = "PRIO_14")]
    Variant14,
    #[serde(rename = "PRIO_15")]
    Variant15,
    #[serde(rename = "PRIO_16")]
    Variant16,

}

impl ToString for ReservPriorityAnyOf {
    fn to_string(&self) -> String {
        match self {
            Self::Variant1 => String::from("PRIO_1"),
            Self::Variant2 => String::from("PRIO_2"),
            Self::Variant3 => String::from("PRIO_3"),
            Self::Variant4 => String::from("PRIO_4"),
            Self::Variant5 => String::from("PRIO_5"),
            Self::Variant6 => String::from("PRIO_6"),
            Self::Variant7 => String::from("PRIO_7"),
            Self::Variant8 => String::from("PRIO_8"),
            Self::Variant9 => String::from("PRIO_9"),
            Self::Variant10 => String::from("PRIO_10"),
            Self::Variant11 => String::from("PRIO_11"),
            Self::Variant12 => String::from("PRIO_12"),
            Self::Variant13 => String::from("PRIO_13"),
            Self::Variant14 => String::from("PRIO_14"),
            Self::Variant15 => String::from("PRIO_15"),
            Self::Variant16 => String::from("PRIO_16"),
        }
    }
}

impl Default for ReservPriorityAnyOf {
    fn default() -> ReservPriorityAnyOf {
        Self::Variant1
    }
}




