/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ReservPriority : Indicates the reservation priority.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ReservPriority {
}

impl ReservPriority {
    /// Indicates the reservation priority.
    pub fn new() -> ReservPriority {
        ReservPriority {
        }
    }
}


