/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RestrictionType : It contains the restriction type ALLOWED_AREAS or NOT_ALLOWED_AREAS.

/// It contains the restriction type ALLOWED_AREAS or NOT_ALLOWED_AREAS.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RestrictionType {
    #[serde(rename = "ALLOWED_AREAS")]
    AllowedAreas,
    #[serde(rename = "NOT_ALLOWED_AREAS")]
    NotAllowedAreas,

}

impl ToString for RestrictionType {
    fn to_string(&self) -> String {
        match self {
            Self::AllowedAreas => String::from("ALLOWED_AREAS"),
            Self::NotAllowedAreas => String::from("NOT_ALLOWED_AREAS"),
        }
    }
}

impl Default for RestrictionType {
    fn default() -> RestrictionType {
        Self::AllowedAreas
    }
}




