/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RoamingOdbAnyOf {
    #[serde(rename = "OUTSIDE_HOME_PLMN")]
    Plmn,
    #[serde(rename = "OUTSIDE_HOME_PLMN_COUNTRY")]
    PlmnCountry,

}

impl ToString for RoamingOdbAnyOf {
    fn to_string(&self) -> String {
        match self {
            Self::Plmn => String::from("OUTSIDE_HOME_PLMN"),
            Self::PlmnCountry => String::from("OUTSIDE_HOME_PLMN_COUNTRY"),
        }
    }
}

impl Default for RoamingOdbAnyOf {
    fn default() -> RoamingOdbAnyOf {
        Self::Plmn
    }
}




