/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SacEventStatus : Contains the network slice status information in terms of the current number of UEs registered  with a network slice, the current number of PDU Sessions established on a network slice or both. 



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SacEventStatus {
    #[serde(rename = "reachedNumUes", skip_serializing_if = "Option::is_none")]
    pub reached_num_ues: Option<Box<crate::models::SacInfo>>,
    #[serde(rename = "reachedNumPduSess", skip_serializing_if = "Option::is_none")]
    pub reached_num_pdu_sess: Option<Box<crate::models::SacInfo>>,
}

impl SacEventStatus {
    /// Contains the network slice status information in terms of the current number of UEs registered  with a network slice, the current number of PDU Sessions established on a network slice or both. 
    pub fn new() -> SacEventStatus {
        SacEventStatus {
            reached_num_ues: None,
            reached_num_pdu_sess: None,
        }
    }
}


