/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SatelliteBackhaulCategory : Indicates the satellite backhaul used.

/// Indicates the satellite backhaul used.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SatelliteBackhaulCategory {
    #[serde(rename = "GEO")]
    Geo,
    #[serde(rename = "MEO")]
    Meo,
    #[serde(rename = "LEO")]
    Leo,
    #[serde(rename = "OTHER_SAT")]
    OtherSat,
    #[serde(rename = "NON_SATELLITE")]
    NonSatellite,

}

impl ToString for SatelliteBackhaulCategory {
    fn to_string(&self) -> String {
        match self {
            Self::Geo => String::from("GEO"),
            Self::Meo => String::from("MEO"),
            Self::Leo => String::from("LEO"),
            Self::OtherSat => String::from("OTHER_SAT"),
            Self::NonSatellite => String::from("NON_SATELLITE"),
        }
    }
}

impl Default for SatelliteBackhaulCategory {
    fn default() -> SatelliteBackhaulCategory {
        Self::Geo
    }
}




