/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScheduledCommunicationTimeRm : This data type is defined in the same way as the 'ScheduledCommunicationTime' data type, but with the OpenAPI 'nullable: true' property. 



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ScheduledCommunicationTimeRm {
    /// Identifies the day(s) of the week. If absent, it indicates every day of the week. 
    #[serde(rename = "daysOfWeek", skip_serializing_if = "Option::is_none")]
    pub days_of_week: Option<Vec<i32>>,
    /// String with format partial-time or full-time as defined in clause 5.6 of IETF RFC 3339. Examples, 20:15:00, 20:15:00-08:00 (for 8 hours behind UTC). 
    #[serde(rename = "timeOfDayStart", skip_serializing_if = "Option::is_none")]
    pub time_of_day_start: Option<String>,
    /// String with format partial-time or full-time as defined in clause 5.6 of IETF RFC 3339. Examples, 20:15:00, 20:15:00-08:00 (for 8 hours behind UTC). 
    #[serde(rename = "timeOfDayEnd", skip_serializing_if = "Option::is_none")]
    pub time_of_day_end: Option<String>,
}

impl ScheduledCommunicationTimeRm {
    /// This data type is defined in the same way as the 'ScheduledCommunicationTime' data type, but with the OpenAPI 'nullable: true' property. 
    pub fn new() -> ScheduledCommunicationTimeRm {
        ScheduledCommunicationTimeRm {
            days_of_week: None,
            time_of_day_start: None,
            time_of_day_end: None,
        }
    }
}


