/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SecondaryRatUsageReport : Secondary RAT Usage Report to report usage data for a secondary RAT for QoS flows.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SecondaryRatUsageReport {
    #[serde(rename = "secondaryRatType")]
    pub secondary_rat_type: crate::models::RatType,
    #[serde(rename = "qosFlowsUsageData")]
    pub qos_flows_usage_data: Vec<crate::models::QosFlowUsageReport>,
}

impl SecondaryRatUsageReport {
    /// Secondary RAT Usage Report to report usage data for a secondary RAT for QoS flows.
    pub fn new(secondary_rat_type: crate::models::RatType, qos_flows_usage_data: Vec<crate::models::QosFlowUsageReport>) -> SecondaryRatUsageReport {
        SecondaryRatUsageReport {
            secondary_rat_type,
            qos_flows_usage_data,
        }
    }
}


