/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SecondaryRatUsageInfo : Secondary RAT Usage Information to report usage data for a secondary RAT for QoS flows and/or the whole PDU session. 



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SecondaryRatUsageInfo {
    #[serde(rename = "secondaryRatType")]
    pub secondary_rat_type: crate::models::RatType,
    #[serde(rename = "qosFlowsUsageData", skip_serializing_if = "Option::is_none")]
    pub qos_flows_usage_data: Option<Vec<crate::models::QosFlowUsageReport>>,
    #[serde(rename = "pduSessionUsageData", skip_serializing_if = "Option::is_none")]
    pub pdu_session_usage_data: Option<Vec<crate::models::VolumeTimedReport>>,
}

impl SecondaryRatUsageInfo {
    /// Secondary RAT Usage Information to report usage data for a secondary RAT for QoS flows and/or the whole PDU session. 
    pub fn new(secondary_rat_type: crate::models::RatType) -> SecondaryRatUsageInfo {
        SecondaryRatUsageInfo {
            secondary_rat_type,
            qos_flows_usage_data: None,
            pdu_session_usage_data: None,
        }
    }
}


