/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SelfLink : It contains the URI of the linked resource.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SelfLink {
    #[serde(rename = "self")]
    pub param_self: Box<crate::models::Link>,
}

impl SelfLink {
    /// It contains the URI of the linked resource.
    pub fn new(param_self: crate::models::Link) -> SelfLink {
        SelfLink {
            param_self: Box::new(param_self),
        }
    }
}


