/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SmallDataRateStatus : It indicates theSmall Data Rate Control Status



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SmallDataRateStatus {
    /// When present, it shall contain the number of packets the UE is allowed to send uplink in the given time unit for the given PDU session (see clause 5.31.14.3 of 3GPP TS 23.501. 
    #[serde(rename = "remainPacketsUl", skip_serializing_if = "Option::is_none")]
    pub remain_packets_ul: Option<i32>,
    /// When present it shall contain the number of packets the AF is allowed to send downlink in the given time unit for the given PDU session (see clause 5.31.14.3 of 3GPP TS 23.501. 
    #[serde(rename = "remainPacketsDl", skip_serializing_if = "Option::is_none")]
    pub remain_packets_dl: Option<i32>,
    /// string with format 'date-time' as defined in OpenAPI.
    #[serde(rename = "validityTime", skip_serializing_if = "Option::is_none")]
    pub validity_time: Option<String>,
    /// When present, it shall indicate number of additional exception reports the UE is allowed to send uplink in the given time  unit for  the given PDU session (see clause 5.31.14.3 of 3GPP TS 23.501. 
    #[serde(rename = "remainExReportsUl", skip_serializing_if = "Option::is_none")]
    pub remain_ex_reports_ul: Option<i32>,
    /// When present, it shall indicate number of additional exception reports the AF is allowed to send downlink  in the given time unit for the given PDU session (see clause 5.31.14.3 in 3GPP TS 23.501 
    #[serde(rename = "remainExReportsDl", skip_serializing_if = "Option::is_none")]
    pub remain_ex_reports_dl: Option<i32>,
}

impl SmallDataRateStatus {
    /// It indicates theSmall Data Rate Control Status
    pub fn new() -> SmallDataRateStatus {
        SmallDataRateStatus {
            remain_packets_ul: None,
            remain_packets_dl: None,
            validity_time: None,
            remain_ex_reports_ul: None,
            remain_ex_reports_dl: None,
        }
    }
}


