/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Ssm : Source specific IP multicast address



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Ssm {
    #[serde(rename = "sourceIpAddr")]
    pub source_ip_addr: Box<crate::models::IpAddr>,
    #[serde(rename = "destIpAddr")]
    pub dest_ip_addr: Box<crate::models::IpAddr>,
}

impl Ssm {
    /// Source specific IP multicast address
    pub fn new(source_ip_addr: crate::models::IpAddr, dest_ip_addr: crate::models::IpAddr) -> Ssm {
        Ssm {
            source_ip_addr: Box::new(source_ip_addr),
            dest_ip_addr: Box::new(dest_ip_addr),
        }
    }
}


