/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// StationaryIndication : Possible values are: - STATIONARY: Identifies the UE is stationary - MOBILE: Identifies the UE is mobile 

/// Possible values are: - STATIONARY: Identifies the UE is stationary - MOBILE: Identifies the UE is mobile 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StationaryIndication {
    #[serde(rename = "STATIONARY")]
    Stationary,
    #[serde(rename = "MOBILE")]
    Mobile,

}

impl ToString for StationaryIndication {
    fn to_string(&self) -> String {
        match self {
            Self::Stationary => String::from("STATIONARY"),
            Self::Mobile => String::from("MOBILE"),
        }
    }
}

impl Default for StationaryIndication {
    fn default() -> StationaryIndication {
        Self::Stationary
    }
}




