/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// StringMatchingRule : A list of conditions for string matching



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StringMatchingRule {
    #[serde(rename = "stringMatchingConditions", skip_serializing_if = "Option::is_none")]
    pub string_matching_conditions: Option<Vec<crate::models::StringMatchingCondition>>,
}

impl StringMatchingRule {
    /// A list of conditions for string matching
    pub fn new() -> StringMatchingRule {
        StringMatchingRule {
            string_matching_conditions: None,
        }
    }
}


