/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SubscribedDefaultQos : Provides the subsribed 5QI and the ARP, it may contain the priority level.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SubscribedDefaultQos {
    /// Unsigned integer representing a 5G QoS Identifier (see clause 5.7.2.1 of 3GPP TS 23.501, within the range 0 to 255. 
    #[serde(rename = "5qi")]
    pub param_5qi: i32,
    #[serde(rename = "arp")]
    pub arp: Box<crate::models::Arp>,
    /// Unsigned integer indicating the 5QI Priority Level (see clauses 5.7.3.3 and 5.7.4 of 3GPP TS 23.501, within the range 1 to 127.Values are ordered in decreasing order of priority, i.e. with 1 as the highest priority and 127 as the lowest priority. 
    #[serde(rename = "priorityLevel", skip_serializing_if = "Option::is_none")]
    pub priority_level: Option<i32>,
}

impl SubscribedDefaultQos {
    /// Provides the subsribed 5QI and the ARP, it may contain the priority level.
    pub fn new(param_5qi: i32, arp: crate::models::Arp) -> SubscribedDefaultQos {
        SubscribedDefaultQos {
            param_5qi,
            arp: Box::new(arp),
            priority_level: None,
        }
    }
}


