/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SupportedGadShapes : Indicates supported GAD shapes.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SupportedGadShapes {
}

impl SupportedGadShapes {
    /// Indicates supported GAD shapes.
    pub fn new() -> SupportedGadShapes {
        SupportedGadShapes {
        }
    }
}


