/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TacInfo : contains tracking area information (tracking area codes).



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TacInfo {
    #[serde(rename = "tacList")]
    pub tac_list: Vec<String>,
}

impl TacInfo {
    /// contains tracking area information (tracking area codes).
    pub fn new(tac_list: Vec<String>) -> TacInfo {
        TacInfo {
            tac_list,
        }
    }
}


