/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Tmgi : Temporary Mobile Group Identity



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Tmgi {
    /// MBS Service ID
    #[serde(rename = "mbsServiceId")]
    pub mbs_service_id: String,
    #[serde(rename = "plmnId")]
    pub plmn_id: Box<crate::models::PlmnId>,
}

impl Tmgi {
    /// Temporary Mobile Group Identity
    pub fn new(mbs_service_id: String, plmn_id: crate::models::PlmnId) -> Tmgi {
        Tmgi {
            mbs_service_id,
            plmn_id: Box::new(plmn_id),
        }
    }
}


