/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TraceData : contains Trace control and configuration parameters.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TraceData {
    /// Trace Reference (see 3GPP TS 32.422).It shall be encoded as the concatenation of MCC, MNC and Trace ID as follows: 'MCC'<MNC'-'Trace ID'The Trace ID shall be encoded as a 3 octet string in hexadecimal representation. Each character in the Trace ID string shall take a value of \"0\" to \"9\", \"a\" to \"f\" or \"A\" to \"F\" and shall represent 4 bits. The most significant character representing the 4 most significant bits of the Trace ID shall appear first  in the string, and the character representing the 4 least significant bit of the Trace ID shall appear last in the string. 
    #[serde(rename = "traceRef")]
    pub trace_ref: String,
    #[serde(rename = "traceDepth")]
    pub trace_depth: crate::models::TraceDepth,
    /// List of NE Types (see 3GPP TS 32.422).It shall be encoded as an octet string in hexadecimal representation. Each character in the string shall take a value of \"0\" to \"9\", \"a\" to \"f\" or \"A\" to \"F\" and shall represent 4 bits. The most significant character representing the 4 most significant bits shall appear first in the string, and the character representing the 4 least significant bit shall appear last in the string.Octets shall be coded according to 3GPP TS 32.422. 
    #[serde(rename = "neTypeList")]
    pub ne_type_list: String,
    /// Triggering events (see 3GPP TS 32.422).It shall be encoded as an octet string in hexadecimal representation. Each character in the string shall take a value of \"0\" to \"9\", \"a\" to \"f\" or \"A\" to \"F\" and shall represent 4 bits. The most significant character representing the 4 most significant bits shall appear first in the string, and the character representing the 4 least significant bit shall appear last in the string. Octets shall be coded according to 3GPP TS 32.422. 
    #[serde(rename = "eventList")]
    pub event_list: String,
    /// String identifying a IPv4 address formatted in the 'dotted decimal' notation as defined in RFC 1166. 
    #[serde(rename = "collectionEntityIpv4Addr", skip_serializing_if = "Option::is_none")]
    pub collection_entity_ipv4_addr: Option<String>,
    #[serde(rename = "collectionEntityIpv6Addr", skip_serializing_if = "Option::is_none")]
    pub collection_entity_ipv6_addr: Option<Box<crate::models::Ipv6Addr>>,
    /// List of Interfaces (see 3GPP TS 32.422).It shall be encoded as an octet string in hexadecimal representation. Each character in the string shall take a value of \"0\" to \"9\", \"a\" to \"f\" or \"A\" to \"F\" and shall represent 4 bits. The most significant character representing the 4 most significant bits shall appear first in the string, and the character representing the 4 least significant bit shall appear last in the string. Octets shall be coded according to 3GPP TS 32.422. If this attribute is not present, all the interfaces applicable to the list of NE types indicated in the neTypeList attribute should be traced. 
    #[serde(rename = "interfaceList", skip_serializing_if = "Option::is_none")]
    pub interface_list: Option<String>,
}

impl TraceData {
    /// contains Trace control and configuration parameters.
    pub fn new(trace_ref: String, trace_depth: crate::models::TraceDepth, ne_type_list: String, event_list: String) -> TraceData {
        TraceData {
            trace_ref,
            trace_depth,
            ne_type_list,
            event_list,
            collection_entity_ipv4_addr: None,
            collection_entity_ipv6_addr: None,
            interface_list: None,
        }
    }
}


