/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TransportProtocol : Possible values are: - UDP: User Datagram Protocol. - TCP: Transmission Control Protocol. 

/// Possible values are: - UDP: User Datagram Protocol. - TCP: Transmission Control Protocol. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TransportProtocol {
    #[serde(rename = "UDP")]
    Udp,
    #[serde(rename = "TCP")]
    Tcp,

}

impl ToString for TransportProtocol {
    fn to_string(&self) -> String {
        match self {
            Self::Udp => String::from("UDP"),
            Self::Tcp => String::from("TCP"),
        }
    }
}

impl Default for TransportProtocol {
    fn default() -> TransportProtocol {
        Self::Udp
    }
}




