/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// UncertaintyEllipsoid : Ellipsoid with uncertainty



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UncertaintyEllipsoid {
    /// Indicates value of uncertainty.
    #[serde(rename = "semiMajor")]
    pub semi_major: f32,
    /// Indicates value of uncertainty.
    #[serde(rename = "semiMinor")]
    pub semi_minor: f32,
    /// Indicates value of uncertainty.
    #[serde(rename = "vertical")]
    pub vertical: f32,
    /// Indicates value of orientation angle.
    #[serde(rename = "orientationMajor")]
    pub orientation_major: i32,
}

impl UncertaintyEllipsoid {
    /// Ellipsoid with uncertainty
    pub fn new(semi_major: f32, semi_minor: f32, vertical: f32, orientation_major: i32) -> UncertaintyEllipsoid {
        UncertaintyEllipsoid {
            semi_major,
            semi_minor,
            vertical,
            orientation_major,
        }
    }
}


