/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// UpIntegrityRm : indicates whether UP integrity protection is required, preferred or not needed for all the traffic on the PDU Session. It shall comply with the provisions defined in table 5.4.3.4-1. 



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpIntegrityRm {
}

impl UpIntegrityRm {
    /// indicates whether UP integrity protection is required, preferred or not needed for all the traffic on the PDU Session. It shall comply with the provisions defined in table 5.4.3.4-1. 
    pub fn new() -> UpIntegrityRm {
        UpIntegrityRm {
        }
    }
}


