/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// UpSecurityRm : This data type is defined in the same way as the 'UpSecurity' data type, but with the OpenAPI 'nullable: true' property. 



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpSecurityRm {
    #[serde(rename = "upIntegr")]
    pub up_integr: crate::models::UpIntegrity,
    #[serde(rename = "upConfid")]
    pub up_confid: crate::models::UpConfidentiality,
}

impl UpSecurityRm {
    /// This data type is defined in the same way as the 'UpSecurity' data type, but with the OpenAPI 'nullable: true' property. 
    pub fn new(up_integr: crate::models::UpIntegrity, up_confid: crate::models::UpConfidentiality) -> UpSecurityRm {
        UpSecurityRm {
            up_integr,
            up_confid,
        }
    }
}


