/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// UriScheme : HTTP and HTTPS URI scheme.

/// HTTP and HTTPS URI scheme.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UriScheme {
    #[serde(rename = "http")]
    Http,
    #[serde(rename = "https")]
    Https,

}

impl ToString for UriScheme {
    fn to_string(&self) -> String {
        match self {
            Self::Http => String::from("http"),
            Self::Https => String::from("https"),
        }
    }
}

impl Default for UriScheme {
    fn default() -> UriScheme {
        Self::Http
    }
}




