/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// UserLocation : At least one of eutraLocation, nrLocation and n3gaLocation shall be present. Several of them may be present. 



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserLocation {
    #[serde(rename = "eutraLocation", skip_serializing_if = "Option::is_none")]
    pub eutra_location: Option<Box<crate::models::EutraLocation>>,
    #[serde(rename = "nrLocation", skip_serializing_if = "Option::is_none")]
    pub nr_location: Option<Box<crate::models::NrLocation>>,
    #[serde(rename = "n3gaLocation", skip_serializing_if = "Option::is_none")]
    pub n3ga_location: Option<Box<crate::models::N3gaLocation>>,
    #[serde(rename = "utraLocation", skip_serializing_if = "Option::is_none")]
    pub utra_location: Option<Box<crate::models::UtraLocation>>,
    #[serde(rename = "geraLocation", skip_serializing_if = "Option::is_none")]
    pub gera_location: Option<Box<crate::models::GeraLocation>>,
}

impl UserLocation {
    /// At least one of eutraLocation, nrLocation and n3gaLocation shall be present. Several of them may be present. 
    pub fn new() -> UserLocation {
        UserLocation {
            eutra_location: None,
            nr_location: None,
            n3ga_location: None,
            utra_location: None,
            gera_location: None,
        }
    }
}


