/*
 * AUSF API
 *
 * AUSF UE Authentication Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AuthenticationInfo : Contains the UE id (i.e. SUCI or SUPI) and the Serving Network Name.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AuthenticationInfo {
    /// String identifying a SUPI or a SUCI.
    #[serde(rename = "supiOrSuci")]
    pub supi_or_suci: String,
    #[serde(rename = "servingNetworkName")]
    pub serving_network_name: String,
    #[serde(rename = "resynchronizationInfo", skip_serializing_if = "Option::is_none")]
    pub resynchronization_info: Option<Box<crate::models::ResynchronizationInfo>>,
    /// String representing a Permanent Equipment Identifier that may contain - an IMEI or IMEISV, as  specified in clause 6.2 of 3GPP TS 23.003; a MAC address for a 5G-RG or FN-RG via wireline  access, with an indication that this address cannot be trusted for regulatory purpose if this  address cannot be used as an Equipment Identifier of the FN-RG, as specified in clause 4.7.7  of 3GPP TS23.316. Examples are imei-012345678901234 or imeisv-0123456789012345. 
    #[serde(rename = "pei", skip_serializing_if = "Option::is_none")]
    pub pei: Option<String>,
    #[serde(rename = "traceData", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub trace_data: Option<Option<Box<crate::models::TraceData>>>,
    /// Identifier of a group of NFs.
    #[serde(rename = "udmGroupId", skip_serializing_if = "Option::is_none")]
    pub udm_group_id: Option<String>,
    #[serde(rename = "routingIndicator", skip_serializing_if = "Option::is_none")]
    pub routing_indicator: Option<String>,
    #[serde(rename = "cellCagInfo", skip_serializing_if = "Option::is_none")]
    pub cell_cag_info: Option<Vec<String>>,
    #[serde(rename = "n5gcInd", skip_serializing_if = "Option::is_none")]
    pub n5gc_ind: Option<bool>,
    /// A string used to indicate the features supported by an API that is used as defined in clause 6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\", \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported. 
    #[serde(rename = "supportedFeatures", skip_serializing_if = "Option::is_none")]
    pub supported_features: Option<String>,
    #[serde(rename = "nswoInd", skip_serializing_if = "Option::is_none")]
    pub nswo_ind: Option<bool>,
    #[serde(rename = "disasterRoamingInd", skip_serializing_if = "Option::is_none")]
    pub disaster_roaming_ind: Option<bool>,
    #[serde(rename = "onboardingInd", skip_serializing_if = "Option::is_none")]
    pub onboarding_ind: Option<bool>,
}

impl AuthenticationInfo {
    /// Contains the UE id (i.e. SUCI or SUPI) and the Serving Network Name.
    pub fn new(supi_or_suci: String, serving_network_name: String) -> AuthenticationInfo {
        AuthenticationInfo {
            supi_or_suci,
            serving_network_name,
            resynchronization_info: None,
            pei: None,
            trace_data: None,
            udm_group_id: None,
            routing_indicator: None,
            cell_cag_info: None,
            n5gc_ind: None,
            supported_features: None,
            nswo_ind: None,
            disaster_roaming_ind: None,
            onboarding_ind: None,
        }
    }
}


