/*
 * AUSF API
 *
 * AUSF UE Authentication Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// EapSession : Contains information related to the EAP session.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EapSession {
    /// contains an EAP packet
    #[serde(rename = "eapPayload", deserialize_with = "Option::deserialize")]
    pub eap_payload: Option<String>,
    /// Contains the Kseaf.
    #[serde(rename = "kSeaf", skip_serializing_if = "Option::is_none")]
    pub k_seaf: Option<String>,
    /// A map(list of key-value pairs) where member serves as key
    #[serde(rename = "_links", skip_serializing_if = "Option::is_none")]
    pub _links: Option<::std::collections::HashMap<String, crate::models::LinksValueSchema>>,
    #[serde(rename = "authResult", skip_serializing_if = "Option::is_none")]
    pub auth_result: Option<crate::models::AuthResult>,
    /// String identifying a Supi that shall contain either an IMSI, a network specific identifier, a Global Cable Identifier (GCI) or a Global Line Identifier (GLI) as specified in clause 2.2A of 3GPP TS 23.003. It shall be formatted as follows  - for an IMSI \"imsi-<imsi>\", where <imsi> shall be formatted according to clause 2.2    of 3GPP TS 23.003 that describes an IMSI.  - for a network specific identifier \"nai-<nai>, where <nai> shall be formatted    according to clause 28.7.2 of 3GPP TS 23.003 that describes an NAI.  - for a GCI \"gci-<gci>\", where <gci> shall be formatted according to clause 28.15.2    of 3GPP TS 23.003.  - for a GLI \"gli-<gli>\", where <gli> shall be formatted according to clause 28.16.2 of    3GPP TS 23.003.To enable that the value is used as part of an URI, the string shall    only contain characters allowed according to the \"lower-with-hyphen\" naming convention    defined in 3GPP TS 29.501. 
    #[serde(rename = "supi", skip_serializing_if = "Option::is_none")]
    pub supi: Option<String>,
    /// A string used to indicate the features supported by an API that is used as defined in clause 6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\", \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported. 
    #[serde(rename = "supportedFeatures", skip_serializing_if = "Option::is_none")]
    pub supported_features: Option<String>,
    #[serde(rename = "pvsInfo", skip_serializing_if = "Option::is_none")]
    pub pvs_info: Option<Vec<crate::models::ServerAddressingInfo>>,
    /// Contains the Master Session Key.
    #[serde(rename = "msk", skip_serializing_if = "Option::is_none")]
    pub msk: Option<String>,
}

impl EapSession {
    /// Contains information related to the EAP session.
    pub fn new(eap_payload: Option<String>) -> EapSession {
        EapSession {
            eap_payload,
            k_seaf: None,
            _links: None,
            auth_result: None,
            supi: None,
            supported_features: None,
            pvs_info: None,
            msk: None,
        }
    }
}


