/*
 * AUSF API
 *
 * AUSF UE Authentication Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EapAuthMethod200Response {
    /// contains an EAP packet
    #[serde(rename = "eapPayload", deserialize_with = "Option::deserialize")]
    pub eap_payload: Option<String>,
    /// URI : /{eapSessionUri}, a map(list of key-value pairs) where member serves as key
    #[serde(rename = "_links")]
    pub _links: ::std::collections::HashMap<String, crate::models::LinksValueSchema>,
}

impl EapAuthMethod200Response {
    pub fn new(eap_payload: Option<String>, _links: ::std::collections::HashMap<String, crate::models::LinksValueSchema>) -> EapAuthMethod200Response {
        EapAuthMethod200Response {
            eap_payload,
            _links,
        }
    }
}


