/*
 * AUSF API
 *
 * AUSF UE Authentication Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ProSeAuthenticationInfo : Contains the UE id (i.e. SUCI) or CP-PRUK ID (in 5gPrukId IE), Relay Service Code and Nonce_1. 



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProSeAuthenticationInfo {
    /// String identifying a SUPI or a SUCI.
    #[serde(rename = "supiOrSuci", skip_serializing_if = "Option::is_none")]
    pub supi_or_suci: Option<String>,
    /// A string carrying the CP-PRUK ID of the remote UE. The CP-PRUK ID is a string in NAI format as specified in clause 28.7.11 of 3GPP TS 23.003. 
    #[serde(rename = "5gPrukId", skip_serializing_if = "Option::is_none")]
    pub param_5g_pruk_id: Option<String>,
    /// Relay Service Code to identify a connectivity service provided by the UE-to-Network relay. 
    #[serde(rename = "relayServiceCode")]
    pub relay_service_code: i32,
    /// contains an Nonce1
    #[serde(rename = "nonce1", deserialize_with = "Option::deserialize")]
    pub nonce1: Option<String>,
    /// A string used to indicate the features supported by an API that is used as defined in clause 6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\", \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported. 
    #[serde(rename = "supportedFeatures", skip_serializing_if = "Option::is_none")]
    pub supported_features: Option<String>,
}

impl ProSeAuthenticationInfo {
    /// Contains the UE id (i.e. SUCI) or CP-PRUK ID (in 5gPrukId IE), Relay Service Code and Nonce_1. 
    pub fn new(relay_service_code: i32, nonce1: Option<String>) -> ProSeAuthenticationInfo {
        ProSeAuthenticationInfo {
            supi_or_suci: None,
            param_5g_pruk_id: None,
            relay_service_code,
            nonce1,
            supported_features: None,
        }
    }
}


