/*
 * AUSF API
 *
 * AUSF UE Authentication Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RgAuthenticationInfo : Contains the UE id (i.e. SUCI) and the authenticated indication.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RgAuthenticationInfo {
    /// Contains the SUCI.
    #[serde(rename = "suci")]
    pub suci: String,
    #[serde(rename = "authenticatedInd")]
    pub authenticated_ind: bool,
    /// A string used to indicate the features supported by an API that is used as defined in clause 6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\", \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported. 
    #[serde(rename = "supportedFeatures", skip_serializing_if = "Option::is_none")]
    pub supported_features: Option<String>,
}

impl RgAuthenticationInfo {
    /// Contains the UE id (i.e. SUCI) and the authenticated indication.
    pub fn new(suci: String, authenticated_ind: bool) -> RgAuthenticationInfo {
        RgAuthenticationInfo {
            suci,
            authenticated_ind,
            supported_features: None,
        }
    }
}


