/*
 * AUSF API
 *
 * AUSF UE Authentication Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TraceDepth {
    #[serde(rename = "MINIMUM")]
    Minimum,
    #[serde(rename = "MEDIUM")]
    Medium,
    #[serde(rename = "MAXIMUM")]
    Maximum,
    #[serde(rename = "MINIMUM_WO_VENDOR_EXTENSION")]
    MinimumWoVendorExtension,
    #[serde(rename = "MEDIUM_WO_VENDOR_EXTENSION")]
    MediumWoVendorExtension,
    #[serde(rename = "MAXIMUM_WO_VENDOR_EXTENSION")]
    MaximumWoVendorExtension,

}

impl ToString for TraceDepth {
    fn to_string(&self) -> String {
        match self {
            Self::Minimum => String::from("MINIMUM"),
            Self::Medium => String::from("MEDIUM"),
            Self::Maximum => String::from("MAXIMUM"),
            Self::MinimumWoVendorExtension => String::from("MINIMUM_WO_VENDOR_EXTENSION"),
            Self::MediumWoVendorExtension => String::from("MEDIUM_WO_VENDOR_EXTENSION"),
            Self::MaximumWoVendorExtension => String::from("MAXIMUM_WO_VENDOR_EXTENSION"),
        }
    }
}

impl Default for TraceDepth {
    fn default() -> TraceDepth {
        Self::Minimum
    }
}




