/*
 * AUSF API
 *
 * AUSF UE Authentication Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// UeAuthenticationCtx : Contains the information related to the resource generated to handle the UE authentication. It contains at least the UE id, Serving Network, the Authentication Method and related EAP information or related 5G-AKA information.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UeAuthenticationCtx {
    #[serde(rename = "authType")]
    pub auth_type: crate::models::AuthType,
    #[serde(rename = "5gAuthData")]
    pub param_5g_auth_data: Box<crate::models::UeAuthenticationCtx5gAuthData>,
    /// A map(list of key-value pairs) where member serves as key
    #[serde(rename = "_links")]
    pub _links: ::std::collections::HashMap<String, crate::models::LinksValueSchema>,
    #[serde(rename = "servingNetworkName", skip_serializing_if = "Option::is_none")]
    pub serving_network_name: Option<String>,
}

impl UeAuthenticationCtx {
    /// Contains the information related to the resource generated to handle the UE authentication. It contains at least the UE id, Serving Network, the Authentication Method and related EAP information or related 5G-AKA information.
    pub fn new(auth_type: crate::models::AuthType, param_5g_auth_data: crate::models::UeAuthenticationCtx5gAuthData, _links: ::std::collections::HashMap<String, crate::models::LinksValueSchema>) -> UeAuthenticationCtx {
        UeAuthenticationCtx {
            auth_type,
            param_5g_auth_data: Box::new(param_5g_auth_data),
            _links,
            serving_network_name: None,
        }
    }
}


